files:
  ".github/mergify.yml": |
    pull_request_rules:
      - name: automatic merge when GitHub branch protection passes on master
        conditions:
          - base=master
          - author=dependabot
        actions:
          merge:
            method: merge

      - name: approve dependabot
        conditions:
          - author=dependabot
        actions:
          review:
            message: auto approve dependabot
