pipeline:

  build:
    image: docker:dind
    commands:
      - docker build -t pinked/magicmirror:latest .
      - docker login -u="chrisns" -p=${DOCKER_PASSWORD}
      - docker push pinked/magicmirror:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  deploy:
    image: docker
    commands:
      - docker deploy --compose-file docker-compose.yml magicmirror
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock