pipeline:

  docker:
    image: plugins/docker
    repo: pinked/magicmirror
    tags:
      - latest
      - ${DRONE_BUILD_NUMBER}
    secrets: [ docker_username, docker_password ]
    when:
      branch: master

  deploy:
    image: docker
    commands:
      - docker deploy --compose-file docker-compose.yml magicmirror
    secrets: [ MQTT_HOST, MQTT_USER, MQTT_PASS, REGION ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: master
