pipeline:

  build:
    image: node:alpine
    commands:
      - npm --silent install
      - node_modules/.bin/napa
      - node_modules/.bin/ng build

  docker:
    image: plugins/docker
    repo: pinked/magicmirror
    tags:
      - latest
      - ${DRONE_BUILD_NUMBER}
    secrets: [ docker_username, docker_password ]

  deploy:
    image: docker
    commands:
      - docker deploy --compose-file docker-compose.yml magicmirror
    secrets: [ MQTT_HOST, MQTT_USER, MQTT_PASS ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
