pipeline:

  docker:
    image: plugins/docker
    repo: pinked/magicmirror
    secrets: [ docker_username, docker_password ]

  deploy:
    image: docker
    commands:
      - docker deploy --compose-file docker-compose.yml magicmirror
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock