version: "3"
services:
  magicmirror:
    networks:
      - proxy
    deploy:
      replicas: 2
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=magicmirror.p.cns.me
        - com.df.port=80
        - com.df.httpsOnly=true
        - com.df.servicePath=/
        - com.df.xForwardedProto=true
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 60s
        max_failure_ratio: 0.3
    image: pinked/magicmirror
    environment:
      - PEER_DISCOVERY_NAME=magicmirror
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
      - DOCKER_VERNEMQ_ALLOW_MULTIPLE_SESSIONS=on

networks:
  proxy:
    external: true