version: "3"
services:
  magicmirror:
    networks:
      - proxy
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.40'
          memory: 128M
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=magicmirror.p.cns.me
        - com.df.port=80
        - com.df.httpsOnly=true
        - com.df.servicePath=/
        - com.df.xForwardedProto=true
        - com.df.usersPassEncrypted=true
        - com.df.users=magicmirror:$6$3CaAozKwM2$MnhzCQw6PZzto0k8.EOm6kpmr7TU245vflQDbOw.sIHy.mhhcWUKpOy3KSdmE5SIw3HmWRMsnjhIQXlBAVHol.
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
    image: pinked/magicmirror:${DRONE_BUILD_NUMBER}
    environment:
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASS=${MQTT_PASS}
      - REGION=${REGION}

networks:
  proxy:
    external: true
